"""Configuration for the Gaia/ASAS-SN variable-star pipeline."""

from pathlib import Path

RANDOM_SEED = 42

PROJECT_ROOT = Path(__file__).resolve().parent
DATA_DIR = PROJECT_ROOT / "data"
RAW_DIR = DATA_DIR / "raw"
INTERIM_DIR = DATA_DIR / "interim"
LIGHTCURVE_CACHE_DIR = DATA_DIR / "lightcurves"
OUTPUT_DIR = PROJECT_ROOT / "outputs"
PLOT_DIR = OUTPUT_DIR / "plots"
MODEL_DIR = OUTPUT_DIR / "models"

GAIA_DR = "gaiadr3"
GAIA_SAMPLE_SIZE = 20000
GAIA_QUERY_RETRIES = 3
GAIA_FALLBACK_SAMPLE_SIZES = (5000, 1000)
GAIA_MIN_PARALLAX_OVER_ERROR = 5.0
GAIA_MAX_RUWE = 1.4

ASASSN_CATALOG_PATH = RAW_DIR / "asassn_catalog.csv"
CROSSMATCH_RADIUS_ARCSEC = 2.0
MAX_LIGHTCURVES = 2000

REQUEST_TIMEOUT_SECONDS = 30
REQUEST_RETRIES = 3
REQUEST_BACKOFF_SECONDS = 2
SKYPATROL_RADIUS_ARCSEC = 2.0
SKYPATROL_THREADS = 2

MIN_LIGHTCURVE_POINTS = 30
MIN_PERIOD_DAYS = 0.05
MAX_PERIOD_DAYS = 100.0
ALIAS_PERIODS_DAYS = (0.5, 1.0, 2.0)
ALIAS_TOLERANCE_DAYS = 0.03

RARE_CLASS_MIN_SAMPLES = 5
TEST_SIZE = 0.25
CV_FOLDS = 5
